version: '3.9'

services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jupyter-local
    ports:
      - 8888:8888
    volumes:
      - ./notebooks:/home/weeravat/notebooks
    environment:
      - JUPYTER_ENABLE_LAB=yes
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
